// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB5L3DkerPYccteReWJHWWU5YKQpfELlw',
    appId: '1:743554030339:web:90ed6d006e440996bb2736',
    messagingSenderId: '743554030339',
    projectId: 'bismillahbudget',
    authDomain: 'bismillahbudget.firebaseapp.com',
    storageBucket: 'bismillahbudget.appspot.com',
    measurementId: 'G-S81RY0050Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2jUxCxC_FiVRHSD-7_usiUv0NPvWRUjA',
    appId: '1:743554030339:android:17adfa01569ec079bb2736',
    messagingSenderId: '743554030339',
    projectId: 'bismillahbudget',
    storageBucket: 'bismillahbudget.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvDzEpR2BXx_49eMvN4pcR3yytd814nAw',
    appId: '1:743554030339:ios:6e07a36ce5409496bb2736',
    messagingSenderId: '743554030339',
    projectId: 'bismillahbudget',
    storageBucket: 'bismillahbudget.appspot.com',
    iosBundleId: 'com.example.bismillahbudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvDzEpR2BXx_49eMvN4pcR3yytd814nAw',
    appId: '1:743554030339:ios:6e07a36ce5409496bb2736',
    messagingSenderId: '743554030339',
    projectId: 'bismillahbudget',
    storageBucket: 'bismillahbudget.appspot.com',
    iosBundleId: 'com.example.bismillahbudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB5L3DkerPYccteReWJHWWU5YKQpfELlw',
    appId: '1:743554030339:web:6eac9c06ebfc52a8bb2736',
    messagingSenderId: '743554030339',
    projectId: 'bismillahbudget',
    authDomain: 'bismillahbudget.firebaseapp.com',
    storageBucket: 'bismillahbudget.appspot.com',
    measurementId: 'G-7HDMCH71WK',
  );
}
